lm-heroku-buildpack-scala-from-scratch: WIP

diff --git a/bin/detect b/bin/detect
--- a/bin/detect
+++ b/bin/detect
@@ -1,26 +1,15 @@
-#!/usr/bin/env bash
-# bin/use <build-dir>
+#!/usr/bin/env sh
+# Usage
+# bin/detect BUILD_DIR
+# BUILD_DIR=$1
 
-BP_DIR=$(cd $(dirname $0)/..; pwd)
-. $BP_DIR/lib/common.sh
-
-BUILD_DIR=$1
-
-## SBT 0.10 allows either *.sbt in the root dir, or project/*.scala or .sbt/*.scala
-if detect_sbt $BUILD_DIR ; then
-  if is_play $BUILD_DIR ; then
-    PLAY_2_X="Play 2.x"
-    DETECTED_PLAY_LANG=$(detect_play_lang $BUILD_DIR);
-    if [ $DETECTED_PLAY_LANG ] ; then
-      echo "$PLAY_2_X - $DETECTED_PLAY_LANG"
-    else
-      echo "$PLAY_2_X"
-    fi
-  else
-    echo "Scala"
-  fi
-  exit 0
+# Detect SBT project
+if [ -f $1/build.sbt ]; then
+    echo "build.sbt found. This is an SBT project"
+    # Comment fancy output for now
+    # echo "Using sbt-$(cat $1/project/build.properties | grep sbt.version | cut -d= -f2)"
+    exit 0
 else
-  (>&2 echo "Could not find a 'build.sbt' file! Please ensure it exists and is checked into Git.")
-  exit 1
+    echo "build.sbt not found. Not an SBT project"
+    exit 1
 fi
